# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: npm test
  publish-master:
    requires:
      - build
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - run: echo "hello world"
  publish-branch:
    requires:
      - build
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - run: echo "hello world from ${CIRCLE_BRANCH} ${CIRCLE_BUILD_NUM}"
      - run: ls

      
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish-branch:
          filters: 
            branches:
              ignore:  
                - master
      - publish-master:
          filters: 
            branches:
              only:  
                - master

